#!/usr/bin/env bash
# build_with_mod.sh — 临时启用一个 example mod 后 build, 然后 revert
#
# 用法:
#   ./scripts/build_with_mod.sh <category> <mod_name>
#   例: ./scripts/build_with_mod.sh cars nissan_gtr_r35
#       ./scripts/build_with_mod.sh cars bmw_template
#
# 主要用途: CI verify 各 example mod 跟 SDK 保持兼容. 本地 dev 通常不用这个,
# 直接编辑 src/app/active_mods.cpp 更直观.
#
# 自动:
#   1. backup src/app/active_mods.cpp
#   2. 写入新 active_mods.cpp 启用指定 mod (注册 profile)
#   3. backup platformio.ini
#   4. 在 platformio.ini build_src_filter 加 +<../examples/<cat>/<mod>/>
#   5. pio run -e round-led-21
#   6. 无论成败, 恢复两个 backup
#
# exit code = pio run 的 exit code

set -uo pipefail   # 不用 -e, 让 cleanup 一定跑

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [[ $# -ne 2 ]]; then
    echo "用法: $0 <category> <mod_name>"
    echo "例:   $0 cars nissan_gtr_r35"
    exit 1
fi

CATEGORY="$1"    # cars / themes
MOD_NAME="$2"    # nissan_gtr_r35 / bmw_template / etc.

MOD_DIR="${REPO_ROOT}/examples/${CATEGORY}/${MOD_NAME}"
if [[ ! -d "${MOD_DIR}" ]]; then
    echo "ERROR: mod 目录不存在: ${MOD_DIR}"
    exit 1
fi

ACTIVE_MODS="${REPO_ROOT}/src/app/active_mods.cpp"
PIO_INI="${REPO_ROOT}/platformio.ini"

# Backup
cp "${ACTIVE_MODS}" "${ACTIVE_MODS}.bak"
cp "${PIO_INI}" "${PIO_INI}.bak"

# Cleanup trap (无论成败恢复)
cleanup() {
    mv "${ACTIVE_MODS}.bak" "${ACTIVE_MODS}" 2>/dev/null || true
    mv "${PIO_INI}.bak" "${PIO_INI}" 2>/dev/null || true
}
trap cleanup EXIT

# 写入临时 active_mods.cpp 启用这个 mod
cat > "${ACTIVE_MODS}" << EOF
// AUTO-GENERATED by scripts/build_with_mod.sh — DO NOT COMMIT
#include "active_mods.h"

namespace raceguard_examples::${MOD_NAME} { void registerProfile(); }

void register_active_mods() {
    raceguard_examples::${MOD_NAME}::registerProfile();
}
EOF

# 在 build_src_filter 行末追加 +<../examples/<cat>/<mod>/>
# 假设 platformio.ini [env:round-led-21] 内 build_src_filter 是单行 "= +<*>" 格式.
# 多行格式 (含 \n 续行) 这条 regex 不 match, 需要手动加 +<.../<mod>/>.
perl -pi -e "s|^(build_src_filter\\s*=.*)|\$1 +<../examples/${CATEGORY}/${MOD_NAME}/>|" "${PIO_INI}"

echo "===> Active_mods + platformio.ini patched to include ${CATEGORY}/${MOD_NAME}"

# pio 命令: CI 上 pip install 装到 PATH; 本地常装 ~/.platformio/penv/bin
PIO_CMD="${PIO_CMD:-pio}"
if ! command -v "${PIO_CMD}" >/dev/null 2>&1; then
    for p in "$HOME/.platformio/penv/bin/pio" /usr/local/bin/pio /opt/homebrew/bin/pio; do
        if [[ -x "$p" ]]; then PIO_CMD="$p"; break; fi
    done
fi

echo "===> Running ${PIO_CMD} run -e round-led-21..."
"${PIO_CMD}" run -e round-led-21
RC=$?

if [[ $RC -eq 0 ]]; then
    echo "✅ Build SUCCESS with ${CATEGORY}/${MOD_NAME}"
else
    echo "❌ Build FAILED with ${CATEGORY}/${MOD_NAME} (exit ${RC})"
fi

exit ${RC}
